apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/tomaszszewczyk/kluster.git
    path: apps/elk/manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

