apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mariadb
    targetRevision: 24.0.0
    helm:
      values: |
        auth:
          database: kimai
          username: kimai
          password: kimai
          rootPassword: rootpassword
        primary:
          persistence:
            enabled: true
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: kimai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

