apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 24.0.6
    helm:
      values: |
        wordpressUsername: admin
        wordpressPassword: admin123
        wordpressBlogName: "Logging Demo"
        service:
          type: ClusterIP
        persistence:
          enabled: true
          size: 5Gi
        mariadb:
          auth:
            rootPassword: rootpassword
            password: wordpress
          primary:
            persistence:
              enabled: true
              size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

